bird-bench/bird-bench.github.io

- index.html
I'm sorry for my bad. I just fixed a mistake in the results of CodeS.
> Fix a mistake in CodeS results

- index.html
OPEN-SQL 9th on EX leaderboard ： EX: 47.74 ,  VES:  48.08
> OPEN-SQL: 9th on  EX leaderBoard

- index.html
Update the experiment results of MCS-SQL to the leaderboard.
> MCS-SQL submission

- index.html
We've added links to CodeS' paper and code in this PR.
Thanks to the BIRD authors for their outstanding contributions to this field!
> Update CodeS paper and code link

- index.html
Hi,
Our paper has been accepted by VLDB 2024. I have updated the paper links.
Thanks.
> DAIL-SQL updated

- index.html
Updating leaderboard with our test results:
```
simple               moderate             challenging          total               
count                949                  555                  285                  1789                
======================================    ACCURACY    =====================================
accuracy             73.02                67.39                51.58                67.86               
===========================================================================================
Finished evaluation
=========================================    VES   ========================================
ves                  80.44                89.18                63.17                80.40 …
```
> Update results with ExSL + granite-20b-code

- index.html
Update with No Oracle Knowledge results for ExSL + granite-20b-code
```
simple               moderate             challenging          total               
count                949                  555                  285                  1789                
======================================    ACCURACY    =====================================
accuracy             64.49                54.41                37.89                57.13               
===========================================================================================
=========================================    VES   ========================================
ves                  80.74                74.82                42.32                72.78 …
```
> Update results with ExSL + granite-20b-code No Oracle Knowledge setting

- index.html
Update scores for Byte-SQL evaluated on May 31, 2024
> update scores for Byte-SQL

- index.html
Update SuperSQL scores (EX and VES) evaluated on June 1, 2024.
> Update SuperSQL scores

- index.html
Update SuperSQL code repo link
> Update SuperSQL code repo link

- index.html
Update scores for ByteBrain (previously Byte-SQL)
> Update scores for ByteBrain

- index.html
Hi BIRD Team,
We would like to change our affiliation name to "ByteDance Infra Lab".
Thank you,
ByteBrain
> Change affiliation for ByteBrain

- index.html
Updating leaderboard based on our latest evaluation results
start calculate
simple               moderate             challenging          total               
count                949                  555                  285                  1789                
======================================    ACCURACY    =====================================
accuracy             73.87                60.72                45.96                65.34               
===========================================================================================
Finished evaluation
=========================================    VES   ========================================
ves                  76.17                64.07                53.62                68.82 …
> Uber Freight - Insights AI submission leaderboard update

- index.html
Adding the results for the 34B version of the ExSL + granite model
> Update results with ExSL + granite-34b-code

- index.html
Adding EX results from our results email: https://gist.github.com/hansonw/369171db34df26d2ce3600a4979fb06e
(For VES we only have the new R-VES score which isn't on the page yet.)
Thank you for evaluating our submission!
> Add Arcwise submission results

- index.html
We just received the official results from the mail. Here is the results file. 
[premai_bird_test_result.txt](https://github.com/user-attachments/files/17054637/premai_bird_test_result.txt)
> add PremSQL-1B in the leaderboard

- index.html
Updating the index.html file to include E-SQL, whose official test results were recorded on September 23, 2024.
> update index.html to add E-SQL

- index.html
Updating the index.html file to include MSL-SQL, whose official test results were recorded on October 7, 2024.
> update index.html to add MSL-SQL eval result

- index.html
Updating our results with improved ExSL + granite-34b-code system.
> Update improved ExSL + granite-34b-code

- index.html
We just received the official results from the mail. Here is the results file.
[interactivet2s_bird_test_result_1108.txt](https://github.com/user-attachments/files/17687916/interactivet2s_bird_test_result_1108.txt)
> add Interactive-T2S in the leaderboard

- index.html
Dear BIRD Team,
I would like to express my sincere gratitude for your support in testing our code. We are planning to update the official results from yesterday’s testing on the leaderboard. The relevant paper and code links will be updated shortly.
Thank you once again for your valuable assistance.
Best regards,
Ethan
Northwestern Polytechnical University
[bird_test_icl_sql_0108_official.txt](https://github.com/user-attachments/files/18357828/bird_test_icl_sql_0108_official.txt)
> Update index.html to include ICL-SQL results

- index.html
We have modified the name of our method and temporarily set the institution to anonymous.
> Update index.html to update method name

- index.html
Update leaderboard with EBA-SQL(former: Eco-SQL) experiment results.
Official test set evaluation results: 
start calculate EX
simple               moderate             challenging          total               
count                949                  555                  285                  1789                
======================================    EX   =====================================
EX                   73.45                59.64                37.89                63.50               
===========================================================================================
Finished EX evaluation for test set
start calculate R-VES
simple               moderate             challenging          total               
count                949                  555 …
> docs: add EBA-SQL to Leaderboard, former: Eco-SQL

- index.html
A little update on the Dev set scores to align our latest ablation experiments.
> Updating the Dev Score for GSR Methods

- index.html
update opensearch-sql arxiv and github
> update opensearch-sql url

- index.html
1. Update entries score
2. Update to unified team name
> Update entry score for Team: AT&T

- index.html
This PR intends to add Queryosity Benchmark results into the Leaderboard.
> Add Queryosity Benchmark Results 

- index.html
This PR seeks to incorporate the evaluation results of OmniSQL into the leaderboard.
> Add OmniSQL Results

- index.html
This PR is for a fix for the date of Queryosity's Entry.
> Fixed Date for Queryosity

- index.html
Update leaderboard with LongShine results
> update index.html 

- index.html
Update the single model leaderboard, add explanation
> update the single leaderboard

- index.html
Update the infomation of the Text-to-SQL scheme 'JT-SQL + XiYanSQL-QwenCoder-32B-2412'.
> Update the leaderboard

- index.html
> update leaderboard: Tencent cloud

- index.html
> Add DBRX number

- index.html
We would like to update the BIRD-Bench with our results.
> Update BIRD leaderboard with JIUTIAN Research results

- index.html
Updated leaderboard with the latest scores for NucliOS.
> updated leaderboard with NucliOS scores

- index.html
Add Jiayin-Pangu-Text2SQL-14B to single-model leaderboard
> Update single-model leaderboard with Jiayin-Pangu-Text2SQL-14B
